### ISSUE TITLE
NTR: L22 sensor model identifier (BODCNVS-1129)

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/W07#1]
We have received a request to add a term to W07 to be used to indicate that a sensor instance is part of the L22 catalogue of sensor models. Open to suggestions.

**Comment by gwemon** [comment]
@alko-k FYI

**Comment by louatbodc** [comment]
We propose the following term to help identify controlled vocabularies such as L22 models which define the model itself.

PREFLABEL:
Model ID

DEFINITION:
An identifier (such as a controlled vocabulary) which defines the unique design of a system or device that is usually mass-produced. The physical characteristics and capabilities will be the same for all product instances made to that design.

**Comment by tvandenberghe** [comment]
"The physical characteristics and capabilities will be the same for all product instances made to that design." I don't know if this is completely accurate as in some cases a capability may be instrument-specific?

Also, maybe this is a nice occasion to streamline the definition of vocab.nerc.ac.uk/collection/W06/current/CLSS0002 and the new ModelID a bit?

Now we have:
An identifier (such as a controlled vocabulary) which defines the unique design of a system or device that is usually mass-produced. The physical characteristics and capabilities will be the same for all product instances made to that design.

and for CLSS0002:

Terms used to classify groups of sensors, instruments, sources of algorithmically computed data (numerical models) or samplers (collectors of water, SPM, sediment, rock, air or biota samples).

"Terms->An identifier (such as a controlled vocabulary)" ?

**Comment by louatbodc** [comment]
Hi @tvandenberghe 

Thanks for your comments. I agree that characteristics and capabilities can be instrument instance specific. Indeed, for example,  instrument instances can have different operating modes which can affect it's capabilities at any one time. I believe these changes would be captured at the instrument instance level in SensorML after inheriting characteristics and capabilities from the model. Thus an instance would have characteristics and capabilities of the model until an operation may subset these.

I understand there is a little discrepancy between CLSS0002 and the proposed new term. To keep threads aligned with their collections I have created a new issue for concepts in W06 in https://github.com/nvs-vocabs/W06/issues/1 as this will need to be discussed with the SWE Marine group.

To help the description of Model ID, perhaps we can be more generalised rather than making a suggestion of an identifier and use:

An identifier that identifies the unique design of a system or device that is usually mass-produced. The physical characteristics and capabilities will be the same for all product instances made to that design.

**Comment by tvandenberghe** [comment]
Hi @louatbodc 

Some suggestions.

If the "such as a controlled vocabulary" is left out people may conflate this term with Model number, http://vocab.nerc.ac.uk/collection/W07/current/IDEN0004/ ? For Model ID, I would explicitly add that vocabularies are to be preferred?  I like how they defined this in DarwinCore: https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact 

And for Model number, have "A name or number, assigned by the manufacturer, which identifies the unique design of a system or device that is usually mass-produced."

For Model ID: An identifier, assigned by a third party, which defines the unique design of a system or device that is usually mass-produced. The physical characteristics and capabilities will be the same for all product instances made to that design, barring physical modifications and changes in configuration modes of specific instrument instances. The identifier should refer to a vocabulary entry.

**Comment by alko-k** [comment]
Hi everyone, what is the status of this term please?

**Comment by louatbodc** [comment]
Hi
Sorry to be a pain and late to reply ( I was on holiday). I actually wonder if an identifier could be a persistent identifier or a local inventory identifier for a model (e.g. a RRID)? Are we being too specific by only allowing vocabularies? Indeed the Marine Profiles community are recommended to use a controlled vocabulary, but other communities may use a different kind of identifier?

I like assigned by third party and assigned by manufacturer.

Model ID:
An identifier, assigned by a third party (for example, a controlled vocabulary), which defines the unique design of a system or device that is usually mass-produced. The physical characteristics and capabilities will be the same for all product instances made to that design, barring subsequent physical modifications and changes in configuration modes of specific instrument instances of the design. 

Model number:
A name or number, assigned by the manufacturer, which identifies the unique design of a system or device that is usually mass-produced.

**Comment by tvandenberghe** [comment]
Hi @louatbodc, that sounds good! If some other communities or institutes use a non-url identifier, that should be usable as well.

**Comment by louatbodc** [comment]
Thanks Thomas

Term - IDEN0015 - Model ID - has now been published.

Term - IDEN0004 - Model number - has now been updated.

Please note it can take up to 24 hours for the updates and new publications to appear on our web services.

Cheers
